"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nha1vlagho**iv#vww*#+a34_1rbbn07pzg&f78!@!!+ge_s-v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps do projeto
    'repasses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'repasses.context_processors.edicao_em_andamento',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Chave primária padrão
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirecionamentos de login
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Caminho da planilha de regras de repasse (anexo 5).
# Provisório: lê das amostras locais. No futuro, as regras serão gerenciadas no
# próprio sistema (banco de dados), atendendo à "fonte única da verdade".
REGRAS_REPASSE_PATH = BASE_DIR / 'amostras' / 'regras_repasse.xlsx'

# Modelos de importação da OMIE (sem dados sensíveis — versionados)
OMIE_PAGAR_TEMPLATE = BASE_DIR / 'repasses' / 'recursos' / 'omie_contas_pagar_modelo.xlsx'
OMIE_RECEBER_TEMPLATE = BASE_DIR / 'repasses' / 'recursos' / 'omie_contas_receber_modelo.xlsx'

# A categoria do contas a RECEBER agora é por grupo de convênio (SUS / CISAMUSEP /
# PARTICULARES) — ver omie.GRUPO_RECEBER. Não há mais categoria única configurável aqui.

# Pasta onde os arquivos gerados ficam disponíveis para download
SAIDAS_DIR = BASE_DIR / 'saidas'

# Pasta de uploads temporários (relatório aguardando revisão antes de exportar)
UPLOADS_DIR = BASE_DIR / 'uploads'

# A revisão envia vários campos por procedimento (honorário, classe, memorizar...).
# Num dia cheio são milhares de atendimentos -> milhares de campos no POST. O padrão
# do Django (1000) estourava (TooManyFieldsSent). Folga p/ ~50 mil atendimentos.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200_000
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024   # 50 MB (corpo do POST da revisão)


# --- Empacotamento como .exe (PyInstaller) -----------------------------------
# Quando roda congelado, os RECURSOS (templates, estáticos, modelos OMIE, planilha
# de regras) vêm de dentro do pacote (sys._MEIPASS, só-leitura) e os DADOS graváveis
# (banco, uploads, saídas) ficam numa pasta "dados" ao lado do executável. Em
# desenvolvimento nada disso roda — segue tudo a partir de BASE_DIR.
import sys

if getattr(sys, 'frozen', False):
    _RES = Path(getattr(sys, '_MEIPASS', BASE_DIR))                 # recursos empacotados
    _DADOS = Path(sys.executable).resolve().parent / 'dados'       # gravável (ao lado do .exe)
    _DADOS.mkdir(parents=True, exist_ok=True)

    DEBUG = True                  # páginas de erro legíveis durante a validação
    ALLOWED_HOSTS = ['*']         # ferramenta local de validação

    TEMPLATES[0]['DIRS'] = [_RES / 'templates']
    STATICFILES_DIRS = [_RES / 'static']
    STATIC_ROOT = _DADOS / 'staticfiles'
    REGRAS_REPASSE_PATH = _RES / 'amostras' / 'regras_repasse.xlsx'
    OMIE_PAGAR_TEMPLATE = _RES / 'repasses' / 'recursos' / 'omie_contas_pagar_modelo.xlsx'
    OMIE_RECEBER_TEMPLATE = _RES / 'repasses' / 'recursos' / 'omie_contas_receber_modelo.xlsx'
    DATABASES['default']['NAME'] = _DADOS / 'db.sqlite3'
    SAIDAS_DIR = _DADOS / 'saidas'
    UPLOADS_DIR = _DADOS / 'uploads'
