# Generated by Django 6.0.6 on 2026-06-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='categoria',
            field=models.CharField(choices=[('medico', 'Médico / Outros'), ('fellow', 'Fellow'), ('residente', 'Residente'), ('preceptor', 'Preceptor'), ('anestesista', 'Anestesista')], default='medico', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='medico',
            name='eh_anestesista',
            field=models.BooleanField(default=False, verbose_name='É anestesista?'),
        ),
        migrations.AddField(
            model_name='medico',
            name='eh_fellow',
            field=models.BooleanField(default=False, verbose_name='É fellow?'),
        ),
        migrations.AddField(
            model_name='medico',
            name='eh_preceptor',
            field=models.BooleanField(default=False, verbose_name='É preceptor?'),
        ),
        migrations.AddField(
            model_name='medico',
            name='razao_social',
            field=models.CharField(blank=True, help_text='Usada como Fornecedor/Cliente na OMIE.', max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='medico',
            name='regra_obs',
            field=models.CharField(blank=True, help_text='Ex.: "R$ 800,00 /semana", "Não recebem em catarata".', max_length=255, verbose_name='Regra / observação da planilha'),
        ),
    ]
