# Generated by Django 6.0.6 on 2026-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0002_medico_categoria_medico_eh_anestesista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoMemorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=255, verbose_name='Procedimento')),
                ('proc_norm', models.CharField(db_index=True, editable=False, max_length=255)),
                ('convenio', models.CharField(blank=True, help_text='Em branco = vale para qualquer convênio.', max_length=120, verbose_name='Convênio')),
                ('conv_norm', models.CharField(blank=True, db_index=True, editable=False, max_length=120)),
                ('medico', models.CharField(blank=True, help_text='Em branco = vale para qualquer médico.', max_length=200, verbose_name='Médico')),
                ('medico_norm', models.CharField(blank=True, db_index=True, editable=False, max_length=200)),
                ('tipo', models.CharField(choices=[('fixo', 'Valor fixo (R$)'), ('percentual', 'Percentual do valor bruto')], default='fixo', max_length=12, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Fixo: em Reais. Percentual: fração (ex.: 0,24 = 24%).', max_digits=12, verbose_name='Valor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('origem', models.CharField(blank=True, help_text='De onde veio (ex.: arquivo do lote que originou).', max_length=200, verbose_name='Origem')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Correção memorizada',
                'verbose_name_plural': 'Correções memorizadas',
                'ordering': ['procedimento', 'convenio', 'medico'],
                'unique_together': {('proc_norm', 'conv_norm', 'medico_norm')},
            },
        ),
    ]
