# Generated by Django 6.0.6 on 2026-06-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0003_correcaomemorizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepasseRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Token do upload')),
                ('dados', models.JSONField(default=dict, verbose_name='Edições')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Rascunho de repasse',
                'verbose_name_plural': 'Rascunhos de repasse',
            },
        ),
    ]
