# Generated by Django 6.0.6 on 2026-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0004_repasserascunho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Token do upload')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(blank=True, max_length=150, verbose_name='Por')),
                ('arquivo_nome', models.CharField(blank=True, max_length=255, verbose_name='Arquivo importado')),
                ('unidade', models.CharField(blank=True, max_length=200, verbose_name='Unidade')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('n_medicos', models.PositiveIntegerField(default=0, verbose_name='Médicos')),
                ('n_repasses', models.PositiveIntegerField(default=0, verbose_name='Repasses')),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total a pagar')),
                ('total_receber', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total a receber')),
                ('pasta_saida', models.CharField(blank=True, max_length=120, verbose_name='Pasta de saída')),
                ('downloads', models.JSONField(default=list, verbose_name='Arquivos gerados')),
                ('auditoria', models.JSONField(default=list, verbose_name='Ajustes manuais')),
                ('fingerprints', models.JSONField(default=list, verbose_name='Atendimentos')),
            ],
            options={
                'verbose_name': 'Lote (histórico)',
                'verbose_name_plural': 'Lotes (histórico)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='repasserascunho',
            name='arquivo_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Arquivo importado'),
        ),
    ]
