# Generated by Django 6.0.6 on 2026-06-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0005_lote_repasserascunho_arquivo_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='medico', max_length=12)),
                ('medico', models.CharField(max_length=200, verbose_name='Profissional')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('clinica', models.CharField(blank=True, max_length=200, verbose_name='Clínica')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('status', models.CharField(choices=[('gerado', 'Gerado'), ('revisado', 'Revisado'), ('enviado', 'Enviado ao médico'), ('pago', 'Pago')], default='gerado', max_length=12, verbose_name='Status')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasses', to='repasses.lote')),
            ],
            options={
                'verbose_name': 'Repasse (acompanhamento)',
                'verbose_name_plural': 'Repasses (acompanhamento)',
                'ordering': ['data', 'clinica', 'medico'],
                'unique_together': {('lote', 'tipo', 'medico', 'data', 'clinica')},
            },
        ),
    ]
