# Generated by Django 6.0.6 on 2026-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0006_repasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraRepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('Cirurgias e Procedimentos', 'Cirurgias e Procedimentos'), ('Exames e Consultas', 'Exames e Consultas'), ('Preceptoria', 'Preceptoria')], default='Exames e Consultas', max_length=40, verbose_name='Classe')),
                ('nome', models.CharField(max_length=255, verbose_name='Procedimento')),
                ('nome_norm', models.CharField(db_index=True, editable=False, max_length=255)),
                ('val_particular', models.CharField(blank=True, help_text='Em branco = não se aplica. "-" = não recebe. Número = R$ (ex.: 25). Percentual com % (ex.: 24%).', max_length=20, verbose_name='Particular')),
                ('val_convenio', models.CharField(blank=True, help_text='Em branco = não se aplica. "-" = não recebe. Número = R$ (ex.: 25). Percentual com % (ex.: 24%).', max_length=20, verbose_name='Convênio')),
                ('val_sus', models.CharField(blank=True, help_text='Em branco = não se aplica. "-" = não recebe. Número = R$ (ex.: 25). Percentual com % (ex.: 24%).', max_length=20, verbose_name='SUS')),
                ('val_oci', models.CharField(blank=True, help_text='Em branco = não se aplica. "-" = não recebe. Número = R$ (ex.: 25). Percentual com % (ex.: 24%).', max_length=20, verbose_name='OCI')),
                ('val_cisa', models.CharField(blank=True, help_text='Em branco = não se aplica. "-" = não recebe. Número = R$ (ex.: 25). Percentual com % (ex.: 24%).', max_length=20, verbose_name='CISA')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Regra de repasse',
                'verbose_name_plural': 'Regras de repasse',
                'ordering': ['classe', 'nome'],
                'unique_together': {('nome_norm', 'classe')},
            },
        ),
    ]
