# Generated by Django 6.0.6 on 2026-06-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0007_regrarepasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='correcaomemorizada',
            name='classe',
            field=models.CharField(blank=True, help_text='Se preenchida, também força a classe (ex.: laudos).', max_length=40, verbose_name='Classe'),
        ),
    ]
