# Generated by Django 6.0.6 on 2026-06-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0008_correcaomemorizada_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=120, verbose_name='Grupo')),
                ('nome', models.CharField(max_length=200, verbose_name='Arquivo')),
                ('conteudo', models.BinaryField(verbose_name='Conteúdo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='repasses.lote')),
            ],
            options={
                'verbose_name': 'Arquivo gerado',
                'verbose_name_plural': 'Arquivos gerados',
                'ordering': ['id'],
            },
        ),
    ]
