# Generated by Django 6.0.6 on 2026-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0009_arquivosaida'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='upload_conteudo',
            field=models.BinaryField(blank=True, null=True, verbose_name='Relatório importado'),
        ),
    ]
