# Generated by Django 6.0.6 on 2026-06-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0010_lote_upload_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='edicoes',
            field=models.JSONField(default=dict, verbose_name='Edições da revisão'),
        ),
    ]
