# Generated by Django 6.0.6 on 2026-06-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0011_lote_edicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='linhas_pagar',
            field=models.JSONField(default=list, verbose_name='Linhas do a pagar'),
        ),
    ]
