# Generated by Django 6.0.6 on 2026-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0012_lote_linhas_pagar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseMemorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=255, verbose_name='Procedimento')),
                ('proc_norm', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('classe', models.CharField(max_length=40, verbose_name='Classe')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('origem', models.CharField(blank=True, max_length=200, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Classe memorizada',
                'verbose_name_plural': 'Classes memorizadas',
                'ordering': ['procedimento'],
            },
        ),
    ]
