# Generated by Django 6.0.6 on 2026-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0013_classememorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do médico (PJ) — é a CHAVE do Fornecedor no contas a pagar da OMIE.', max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='razao_social',
            field=models.CharField(blank=True, help_text='Razão social do médico (PJ).', max_length=200, verbose_name='Razão Social'),
        ),
    ]
