# Generated by Django 6.0.6 on 2026-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0014_medico_cnpj_alter_medico_razao_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Chave PIX do médico (para pagamento) — opcional.', max_length=80, verbose_name='Chave PIX'),
        ),
    ]
