# Generated by Django 6.0.6 on 2026-07-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0015_medico_chave_pix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(db_index=True, max_length=7, verbose_name='Mês (AAAA-MM)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (+ acréscimo / − desconto)')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repasses.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Ajuste mensal',
                'verbose_name_plural': 'Ajustes mensais',
                'ordering': ['ano_mes', 'medico__nome'],
                'unique_together': {('ano_mes', 'medico')},
            },
        ),
    ]
