# Generated by Django 6.0.6 on 2026-07-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0016_ajustemensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemRepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Dia')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Confirmado em')),
                ('criado_por', models.CharField(blank=True, max_length=150, verbose_name='Por')),
            ],
            options={
                'verbose_name': 'Dia sem repasse (confirmado)',
                'verbose_name_plural': 'Dias sem repasse (confirmados)',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome fantasia da clínica/PJ do médico.', max_length=200, verbose_name='Nome Fantasia'),
        ),
    ]
