# Generated by Django 6.0.6 on 2026-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repasses', '0017_diasemrepasse_medico_nome_fantasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token do upload'),
        ),
    ]
